{{- $seed := .Values.secretSeed | required "secretSeed is required" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak-realm.labels" . | nindent 4 }}
data:
  realm.json: |
    {{- include "keycloak-realm.json" . | nindent 4 }}
