{{- if .Values.apps.find.enabled }}
{{- $_ := .Values.secretSeed | required "secretSeed is required" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: find-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-configuration.labels" . | nindent 4 }}
    app: find
  annotations:
    {{- include "reflector.annotations" "lasuite-find" | nindent 4 }}
type: Opaque
stringData:
  # Django secret key
  DJANGO_SECRET_KEY: "{{ include "getSecret" (dict "root" . "id" "find-django-secret") }}"

  # Django superuser password
  DJANGO_SUPERUSER_PASSWORD: "{{ include "getSecret" (dict "root" . "id" "find-superuser") }}"

  # Database credentials
  DB_PASSWORD: "{{ include "getSecret" (dict "root" . "id" "find-db") }}"
  POSTGRES_PASSWORD: "{{ include "getSecret" (dict "root" . "id" "find-db") }}"

  # Redis credentials (DB /9 and /10)
  REDIS_URL: "redis://:{{ include "getSecret" (dict "root" . "id" "redis") }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}/9"
  DJANGO_CELERY_BROKER_URL: "redis://:{{ include "getSecret" (dict "root" . "id" "redis") }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}/10"

  # OIDC client credentials
  OIDC_RP_CLIENT_ID: "find"
  OIDC_RP_CLIENT_SECRET: "{{ include "getSecret" (dict "root" . "id" "find-oidc-client") }}"

  # OpenSearch credentials
  OPENSEARCH_PASSWORD: "{{ include "getSecret" (dict "root" . "id" "opensearch-admin") }}!Os0"
{{- end }}
