{{- if .Values.apps.people.enabled }}
{{- $_ := .Values.secretSeed | required "secretSeed is required" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: people-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-configuration.labels" . | nindent 4 }}
    app: people
  annotations:
    {{- include "reflector.annotations" "lasuite-people" | nindent 4 }}
type: Opaque
stringData:
  # Django secret key
  DJANGO_SECRET_KEY: "{{ include "getSecret" (dict "root" . "id" "people-django-secret") }}"

  # Django superuser password
  DJANGO_SUPERUSER_PASSWORD: "{{ include "getSecret" (dict "root" . "id" "people-superuser") }}"

  # Database credentials
  DB_PASSWORD: "{{ include "getSecret" (dict "root" . "id" "people-db") }}"
  POSTGRES_PASSWORD: "{{ include "getSecret" (dict "root" . "id" "people-db") }}"

  # Redis credentials (DB /5 and /6)
  REDIS_URL: "redis://:{{ include "getSecret" (dict "root" . "id" "redis") }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}/5"
  DJANGO_CELERY_BROKER_URL: "redis://:{{ include "getSecret" (dict "root" . "id" "redis") }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}/6"

  # S3 credentials
  AWS_S3_ACCESS_KEY_ID: "{{ include "getSecret" (dict "root" . "id" "s3-access") }}"
  AWS_S3_SECRET_ACCESS_KEY: "{{ include "getSecret" (dict "root" . "id" "s3-secret") }}"

  # OIDC client credentials
  OIDC_RP_CLIENT_ID: "people"
  OIDC_RP_CLIENT_SECRET: "{{ include "getSecret" (dict "root" . "id" "people-oidc-client") }}"
{{- end }}
